language: ruby
rvm:
  - 2.6.3
install:
  - bundle install
script:
  - bundle exec jekyll build
deploy:
  local_dir: _site
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  
  keep_history: false
  on:
    branch: main