title: 'Data standards'
description: test
url: https://wethecatalysts.github.io/formats-and-identifiers
baseurl: /formats-and-identifiers
feedbackUrl: https://airtable.com/shrcSFfRzVT0bucct?prefill_Recipe+Page=https://wethecatalysts.github.io/formats-and-identifiers/
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: false
  exclude:
    - README.md
navigation:
  -
    path: '/'
    title: Home
  -
    path: '/new.html'
    title: Propose a new challenge
